optimizer:
    SGD:
      dampening: 0
      lr: 0.01
      momentum: 0.9
      nesterov: true
      weight_decay: 0
    #ASGD:
     # lr: 0.001

scheduler:
    - CosineAnnealingLR:
        T_max: 50
        eta_min: 0.00001
        verbose: false
    - ExponentialLR:
        gamma: 0.96
        last_epoch: -1
        verbose: false
